#! /bin/sh
sxhkd &
~/.config/polybar/launch.sh 

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
